### ISSUE TITLE
'hit counter' to Fatplants

### ISSUE THREAD

**Issue by Yongfang-Qin** [MU-DBL/fatplants_old#18]
Count of the number of people who visit my website automatically

**Comment by govardhanrk** [comment]
This can be implmented from the frontend side using the https://www.cutercounter.com/ portal.

I have generated the below code snippet from **https://www.cutercounter.com/** for **https://fatplants.net/** url which can be integrated in HTML code of fatsplant webpage.

```
<!-- Start of CuterCounter Code -->
<a href="https://www.cutercounter.com/" target="_blank"><img src="https://www.cutercounter.com/hits.php?id=hexpkaop&nd=6&style=3" border="0" alt="visitor counter"></a><a href="https://www.ttu.cc/" target="_blank">url shortener</a>
<!-- End of CuterCounter Code -->
```

In case URL change or different counter style needed,
1. visit https://www.cutercounter.com/
2. Enter fatsplant website URL
3. click on "Get your counter HTML code"
4. integrate the generated HTML code with fatsplant webpage
