### ISSUE TITLE
Datasets page

### ISSUE THREAD

**Issue by Naveed319** [MU-DBL/fatplants_old#20]
Redesign the Dataset according the layout defined the pdf

![image](https://github.com/MU-DBL/fatplants/assets/45944298/976c5bdc-a539-469c-aa6a-6f744611d4ce)

**Comment by Yongfang-Qin** [comment]
The table is incorrect. The table here should as same as the current one

**Comment by Yongfang-Qin** [comment]
Assign to Ganesh for the graduate project
