### ISSUE TITLE
Details page

### ISSUE THREAD

**Issue by Naveed319** [MU-DBL/fatplants_old#21]
Modify the details page(which is redirected when we click details button in the dataset page) according the image below:

![image](https://github.com/MU-DBL/fatplants/assets/45944298/5330c17c-3305-470b-802d-ca8d5869a8c7)

**Comment by Yongfang-Qin** [comment]
The page doesn't show the layout of each section (summary, alignments, etc.)

**Comment by Naveed319** [comment]
its the same as the current search page. I'm taking care of this page!
